### ISSUE TITLE
UI should store cookie for saving a list of ASNs the user is interested in.

### ISSUE THREAD

**Issue by c-morris** [UConnBGP/REU-Repo#1]
When users return to the site, they will probably be interested in viewing the results for the same ASNs or list of ASNs. We should store these queries in a cookie.

**Comment by sdb2139** [comment]
are there currently any other spots in the ui that use cookies?

**Comment by c-morris** [comment]
No, none at the moment.

**Comment by sdb2139** [comment]
I have finished a js file for managing cookies, and I am working at making another file that manages cookies with angular
[forecast-cookies.zip](https://github.com/UConnBGP/REU-Repo/files/3248693/forecast-cookies.zip)

**Comment by sdb2139** [comment]
from what I have seen from the forecast-ui code, the easiest solution for writing to cookies will be within the loadTable() method.

**Comment by iReynaldo** [comment]
I disagree, a cookie's functionality should be immediately available from visiting the site alone.

**Comment by iReynaldo** [comment]
Create a function that updates the cookie inside that method.

**Comment by sdb2139** [comment]
^ I was planning on doing that

**Comment by sdb2139** [comment]
After testing the ForecastUI, I have discovered that browsers automatically do this through caching, and after running it multiple times it already has this feature (at least on firefox).
In the interest of not reinventing the wheel, we can probably mark this as done, and I am shifting focus onto another issue.
